name = "Amr Maghraby"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "Full Stack Engineer"
company = 'Webalo'
# company = '<a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>'
location = "Egypt"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"

[social]
  email = "amr.alkeleay@gmail.com"
  github = "https://github.com/AmrMaghraby"
  twitter = "https://twitter.com/IAm3amour"
  # patreon = "razonyang"
  # paypal = "razonyang"
  # rss = "" # Disable RSS link
